name: Run BOT and Upload to Drive

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "* * * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - run: jupyter nbconvert --to notebook --execute BOT_FPO_DATA.ipynb --output executed.ipynb

      - run: python upload_to_drive.py
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
